openapi: 3.0.0
info:
  title: Reusable Header Parameters
  version: "1.0"
  description: Berlin Group NextGenPSD2– Version 1.3.4
components:
  parameters:
    Content-Type-JSON:
      in: header
      description: "application/json"
      name: Content-Type
      required: true
      schema:
        type: string
    Content-Type-XML:
      in: header
      description: "application/xml"
      name: Content-Type
      required: true
      schema:
        type: string
    X-Request-ID:
      in: header
      description: "ID of the request, unique to the call, as determined by the initiating party."
      name: X-Request-ID
      required: true
      schema:
        type: string
        format: uuid
    Consent-ID:
      in: header
      description: 'Shall be contained since "Establish Consent Transaction" was performed via this API before.'
      name: Consent-ID
      required: true
      schema:
        type: string
    PSU-IP-Address:
      in: header
      description: "The forwarded IP Address header field consists of the corresponding HTTP request IP Address field between PSU and TPP. It shall be contained if and only if this request was actively initiated by the PSU."
      name: PSU-IP-Address
      required: false
      schema:
        type: string
    Accept:
      in: header
      description: ''
      name: Accept
      required: false
      schema:
        type: string
    Location:
      in: header 
      description: 'Location of the created resource (if created)'
      name: Location
      required: flase
      schema:
        type: string consentStatus